[package]
name = "trustify-query"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
utoipa = { workspace = true }
